#server port
server:
  port: 3030

#datasource properties
spring:
  datasource:
     url : jdbc:mysql://localhost:3306/jrtp
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     dialect: org.hibernate.dialect.MySQL8Dialect
     hikari:
      maximum-pool-size: 50
      idleTimeout: 600000
      maxLifetime: 1800000 
      connectionTimeout: 30000   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  
    
  mail: 
    host: smtp.gmail.com
    username: slimprince777@gmail.com
    password: vwiefcugfhdlmceg
    port: 587
    properties:
       mail:
          smtp:
               starttls:
                   enable: true
       
               ssl:
                  protocols: TLSv1.2 
